'use client';
import { useState } from 'react';
import { Brand } from '../components/Brand';
const friends=[['AR','Aarav','owes you','+$48.20','coral'],['MY','Maya','owes you','+$26.50','purple'],['SM','Sam','you owe','−$18.40','blue']];
const expenses=[['🍜','Dinner at Roadhouse','Pokhara Weekend · Today','$84.00','+$21.00'],['📶','Internet','Apartment · Yesterday','$45.00','−$15.00'],['🚕','Airport taxi','Pokhara Weekend · Monday','$36.00','+$9.00']];
export default function Home(){const [theme,setTheme]=useState<'dark'|'light'>('dark');const [showLogin,setShowLogin]=useState(false);return <div className={`app design-${theme}`}>
<aside className="sidebar"><Brand/><div className="brand-context"><span>SETTLR</span><strong>Shared Expenses</strong></div><nav aria-label="Primary navigation">{['Home','Personal','Groups','Activity','You'].map((item,i)=><a className={i===0?'active':''} href={`#${item.toLowerCase()}`} key={item}><span aria-hidden="true">{['⌂','◌','♧','♧','◎'][i]}</span>{item}{item==='Groups'&&<i className="nav-dot"/>}</a>)}</nav><div className="sidebar-premium"><p>UPGRADE TO PREMIUM</p><span>Unlock smart reminders & unlimited active group tracking.</span><button>Get Pro</button></div><button className="profile"><span className="avatar avatar-photo">SW</span><span><strong>Sam Wilson</strong><small>sam@settlr.app</small></span><span aria-hidden="true">⚙</span></button></aside>
<main className="content"><header className="topbar"><div><p className="kicker">SETTLR OVERVIEW</p><h1>Settlr Overview</h1><p className="subtitle">Track and settle split expenses instantly across your network</p></div><div className="top-actions"><label className="search"><span>⌕</span><input aria-label="Search transactions and friends" placeholder="Search transactions, friends..."/></label><button className="icon-button" aria-label="Notifications">♧</button><button className="button button-ghost" onClick={()=>setShowLogin(true)}>Sign in</button><button className="button button-primary">＋ Add expense</button><button className="theme-switch" onClick={()=>setTheme(theme==='dark'?'light':'dark')} aria-label="Switch theme">{theme==='dark'?'☼':'☾'}</button></div></header>
<div className="overview-grid"><section className="balance-card hero-balance"><div className="card-head"><span>Total balance</span><b>•••</b></div><strong className="hero-money">+$56.30</strong><span className="detail">Across 3 groups · USD</span><div className="balance-split"><div><span className="circle positive">↙</span><small>YOU ARE OWED</small><strong>+$74.70</strong></div><div><span className="circle negative">↗</span><small>YOU OWE</small><strong>−$18.40</strong></div></div></section><section className="quick-actions"><p className="kicker">QUICK ACTIONS</p><button className="quick-primary">＋ <span>Add expense</span></button><button>▣ <span>Settle up</span></button><button>♧ <span>New group</span></button><button>♧ <span>Remind</span></button></section><section className="friends"><div className="section-heading"><div><p className="kicker">BALANCES</p><h2>Friends</h2></div><a href="#friends">See all</a></div>{friends.map(([initials,name,status,amount,color])=><div className="friend-row" key={name}><span className={`friend-avatar ${color}`}>{initials}</span><div><strong>{name}</strong><small className={status==='you owe'?'negative-text':''}>{status}</small></div><b className={status==='you owe'?'negative-text':'positive-text'}>{amount}</b><span className="qr">▦</span></div>)}</section></div>
<div className="lower-grid"><section className="recent"><div className="section-heading"><div><p className="kicker">RECENT</p><h2>Latest expenses</h2></div><button className="filter" aria-label="Filter expenses">▽</button></div>{expenses.map(([icon,title,meta,total,share])=><div className="expense-card" key={title}><span className="expense-icon">{icon}</span><div><strong>{title}</strong><small>{meta}</small></div><div className="expense-total"><small>TOTAL SPENT</small><span>{total}</span></div><div className="expense-total"><small>YOUR SHARE</small><span className={share.startsWith('−')?'negative-text':'positive-text'}>{share}</span></div><b className="chevron">›</b></div>)}</section><aside className="insight"><span className="insight-icon">✣</span><h3>August insight</h3><p>You spent 12% less on dining this month. Keep it up! Settling early could improve your credit credibility index.</p><a href="#report">View full report →</a></aside></div></main>
{showLogin&&<div className="modal-backdrop" role="presentation" onClick={()=>setShowLogin(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="login-title" onClick={event=>event.stopPropagation()}><button className="modal-close" onClick={()=>setShowLogin(false)} aria-label="Close sign in">×</button><p className="kicker">WELCOME BACK</p><h2 id="login-title">Keep your circle balanced</h2><p className="modal-copy">Sign in to see your real groups, balances, and recent activity.</p><label>Email<input type="email" placeholder="you@example.com"/></label><label>Password<input type="password" placeholder="••••••••"/></label><button className="button button-primary button-wide" onClick={()=>setShowLogin(false)}>Sign in securely</button></section></div>}</div>}
